// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ATSFormatCheck(arg1) {
  return window['go']['main']['App']['ATSFormatCheck'](arg1);
}

export function ATSFullCheck(arg1, arg2) {
  return window['go']['main']['App']['ATSFullCheck'](arg1, arg2);
}

export function CreateCV(arg1) {
  return window['go']['main']['App']['CreateCV'](arg1);
}

export function CreateEntry(arg1) {
  return window['go']['main']['App']['CreateEntry'](arg1);
}

export function CreateSection(arg1) {
  return window['go']['main']['App']['CreateSection'](arg1);
}

export function DeleteCV(arg1) {
  return window['go']['main']['App']['DeleteCV'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DeleteGeminiAPIKey() {
  return window['go']['main']['App']['DeleteGeminiAPIKey']();
}

export function DeleteSection(arg1) {
  return window['go']['main']['App']['DeleteSection'](arg1);
}

export function GetCV(arg1) {
  return window['go']['main']['App']['GetCV'](arg1);
}

export function GetGeminiAPIKey() {
  return window['go']['main']['App']['GetGeminiAPIKey']();
}

export function ListCVs() {
  return window['go']['main']['App']['ListCVs']();
}

export function ReorderEntry(arg1, arg2) {
  return window['go']['main']['App']['ReorderEntry'](arg1, arg2);
}

export function ReorderSection(arg1, arg2) {
  return window['go']['main']['App']['ReorderSection'](arg1, arg2);
}

export function SavePDF(arg1, arg2) {
  return window['go']['main']['App']['SavePDF'](arg1, arg2);
}

export function SetGeminiAPIKey(arg1) {
  return window['go']['main']['App']['SetGeminiAPIKey'](arg1);
}

export function TranslateCV(arg1) {
  return window['go']['main']['App']['TranslateCV'](arg1);
}

export function TranslateFullCV(arg1, arg2) {
  return window['go']['main']['App']['TranslateFullCV'](arg1, arg2);
}

export function UpdateCV(arg1) {
  return window['go']['main']['App']['UpdateCV'](arg1);
}

export function UpdateEntry(arg1) {
  return window['go']['main']['App']['UpdateEntry'](arg1);
}

export function UpdateSection(arg1) {
  return window['go']['main']['App']['UpdateSection'](arg1);
}
