// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cv} from '../models';
import {atsscore} from '../models';
import {translate} from '../models';

export function ATSFormatCheck(arg1:cv.CV):Promise<atsscore.FinalReport>;

export function ATSFullCheck(arg1:cv.CV,arg2:string):Promise<atsscore.FinalReport>;

export function CreateCV(arg1:cv.CreateCVRequest):Promise<cv.CV>;

export function CreateEntry(arg1:cv.CreateEntryRequest):Promise<cv.Entry>;

export function CreateSection(arg1:cv.CreateSectionRequest):Promise<cv.Section>;

export function DeleteCV(arg1:string):Promise<void>;

export function DeleteEntry(arg1:string):Promise<void>;

export function DeleteGeminiAPIKey():Promise<void>;

export function DeleteSection(arg1:string):Promise<void>;

export function GetCV(arg1:string):Promise<cv.CV>;

export function GetGeminiAPIKey():Promise<string>;

export function ListCVs():Promise<Array<cv.CV>>;

export function ReorderEntry(arg1:string,arg2:string):Promise<void>;

export function ReorderSection(arg1:string,arg2:string):Promise<void>;

export function SavePDF(arg1:string,arg2:string):Promise<void>;

export function SetGeminiAPIKey(arg1:string):Promise<void>;

export function TranslateCV(arg1:translate.TranslateRequest):Promise<translate.TranslateResponse>;

export function TranslateFullCV(arg1:cv.CV,arg2:string):Promise<cv.CV>;

export function UpdateCV(arg1:cv.CV):Promise<void>;

export function UpdateEntry(arg1:cv.Entry):Promise<void>;

export function UpdateSection(arg1:cv.Section):Promise<void>;
